### ISSUE TITLE
problems loading data from configs_manner

### ISSUE THREAD

**Issue by davihdsantos** [Natalnet/ncovid-ml-modules#35]
configs_manner only loads data from configure.json when import configs_manner is called. If i change configure.json and run the code again, the new data won't load since the module itself wont reload  (it seems python wont import the module again if its already loaded). i have to manually reload the model with

from importlib import reload
reload(configs_manner)

to get the data to configs_manner object.

**Comment by EmersonVilar** [comment]
This only happens on jupyter notebook or in terminal too?

**Comment by davihdsantos** [comment]
its a jupyter related problem. closing.
